image: Visual Studio 2019
platform: x64
install:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
build_script:
    - cmake -GNinja -B_gen -H. -DBUILD_TESTING=1 -DCMAKE_TOOLCHAIN_FILE=toolchains/clang-ci-appveyor.cmake
    - ninja -C _gen
test_script:
    - cd _gen/tests
    - xcopy /s C:\OpenSSL-v111-Win64\bin .
    - audiotube_tests.exe