image: Visual Studio 2019
platform: x64
install:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
build_script:
    - cmake -GNinja -B_genRelease -H. -DCMAKE_BUILD_TYPE=Release -DQt5_DIR="C:/Qt/5.14/msvc2017_64/lib/cmake/Qt5"
    - cd _genRelease
    - ninja
test_script:
    - cd tests
    - cmd: audiotube_tests.exe