image: Visual Studio 2019
platform: x64
install:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
build_script:
    - cmake -GNinja -B_genRelease -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH="C:\Qt\5.14\mingw73_64"
    - cd _genRelease
    - ninja