image: Visual Studio 2019
platform: x64
install:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
build_script:
    - cmake -GNinja -B_gen -H. -DCMAKE_BUILD_TYPE=Release -DQt5_DIR="C:/Qt/5.14/msvc2017_64/lib/cmake/Qt5"
    - cd _gen
    - ninja
test_script:
    - cd tests
    - C:/Qt/5.14/msvc2017_64/bin/windeployqt.exe audiotube_tests.exe
    - xcopy /s C:/OpenSSL-v111-Win64/bin .
    - audiotube_tests.exe